# Development Dockerfile
FROM node:22-alpine

WORKDIR /app

# 1. Copia os arquivos de dependências
COPY package*.json ./

# 2. Copia a pasta prisma ANTES do install
COPY prisma ./prisma/

# 3. Instala as dependências
RUN npm install

# 3. Agora o install vai funcionar, pois o prisma generate achará o schema
RUN npm install

# 4. Copia o restante dos arquivos
COPY . .

# Expose port
EXPOSE 3000

# Start in development mode
CMD ["npm", "run", "start:dev"]
